### ISSUE TITLE
トップページ日本語化

### ISSUE THREAD

**Issue by goofmint** [DevRelConTokyo/2023#24]

**Comment by suzukin** [comment]
ペンディング中。MacのChromeとEdgeでは英語設定で日本語が表示されてしまうバグがあり、この実装を進めると英語圏のスピーカー参加者に強制的に日本語が表示されてしまうのではなかと cc @nigiiro-taro 
https://devreljp.slack.com/archives/C047ZM4CBM0/p1672921448770459
