### ISSUE TITLE
スピーカーインタビューの埋め込み

### ISSUE THREAD

**Issue by suzukin** [DevRelConTokyo/2023#37]

**Comment by goofmint** [comment]
speakersシートのinterview_urlを使います。

`sh getData.sh` を実行すると、_data/speakers.json が更新されます（処理はたぶんエラーが出るでしょうが気にしないでください。OGP作成などで他にも必要なライブラリがあるだけです）。

interview_urlは `https://www.youtube.com/watch?v=rXAC35g4Cys` みたいになっているので、以下のような手順で使います。

1. `https://www.youtube.com/watch?v=` を空文字にする
2. 取得したキー `rXAC35g4Cys` を使って埋め込み用文字列を作る
3. Jekyllで描画する
